version: '3.8'

services:
  buda_task:
    build:
      context: .
      dockerfile: Dockerfile
    image: buda_task
    container_name: drf_api
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    volumes:
      - ./pyproject.toml:/app/pyproject.toml
      - ./.prospector.yaml:/app/.prospector.yaml
      - ./db.sqlite3:/app/db.sqlite3
      - ./manage.py:/app/manage.py
      - ./budapi:/app/budapi
      - ./model:/app/model
    env_file:
      - .env
    stdin_open: true
    tty: true
