version: '3.8'

services:
  buda_task:
    build:
      context: .
      dockerfile: Dockerfile
    image: buda_task
    container_name: drf_api
    command: python manage.py runserver 0.0.0.0:4000
    ports:
      - 4000:4000
    volumes:
      - ./manage.py:/app/manage.py
      - ./budapi:/app/budapi
      - ./pyproject.toml:/app/pyproject.toml
    stdin_open: true
    tty: true